version: 0.2
phases:
  install:
    commands:
    - echo install step...
  pre_build:
    commands:
    - echo logging in to AWS ECR...
    - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
    - echo build Docker image on `date`
    - cd src
    - docker build -t Capstone2Group1Image:latest .
    - docker tag Capstone2Group1Image:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/capstone2/group1afternoon:latest
post_build:
  commands:
    - echo build Docker image complete `date`
    - echo push latest Docker images to ECR...
    - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/capstone2/group1afternoon:latest



